# docker-compose -f docker-compose.test.yml up --build
version: "3"

services:
  app-test:
    build:
      context: ../
      dockerfile: docker/Dockerfile.test
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://database-test:27017
    restart: always
    depends_on:
      - database-test
  
  database-test:
    image: mongo:4.1.6
    restart: always
    ports:
      - 27017:27017