FROM node:alpine

WORKDIR /home/cpf-cnpj-management/app/test/backend

ENV NODE_ENV test

COPY package*.json ./
RUN npm install
RUN npm install -g mocha

COPY . .

EXPOSE 3000

CMD mocha src/tests/userTests.js