# docker-compose -f docker-compose.develop.yml up --build
version: "3"

services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile.develop
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://database:27017
    restart: always
    depends_on:
      - database

  database:
    image: mongo
    container_name: "database"
    restart: always
    ports:
      - 27017:27017